/* Fixed film follows ordinary document scroll. No pinning or hidden headlines. */
(() => {
  const FRAME_COUNT=140, CONCURRENCY=3;
  const canvas=document.querySelector('#film-canvas'),ctx=canvas.getContext('2d'),toggle=document.querySelector('#motion-toggle');
  const motionQuery=matchMedia('(prefers-reduced-motion: reduce)'),connection=navigator.connection;
  const constrained=connection?.saveData||/(^|-)2g|3g/.test(connection?.effectiveType||'');
  let paused=motionQuery.matches||constrained,images=[],current=-1,target=0,scheduled=false,generation=0,loading=false;
  let folder=innerWidth<768?'mobile':'desktop';
  function size(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);current=-1;}
  function draw(){scheduled=false;if(paused)return;const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);target=Math.min(FRAME_COUNT-1,Math.round(scrollY/max*(FRAME_COUNT-1)));let nearest=-1,distance=Infinity;images.forEach((image,index)=>{if(image&&Math.abs(index-target)<distance){nearest=index;distance=Math.abs(index-target);}});if(nearest>=0&&nearest!==current){const image=images[nearest],s=Math.max(canvas.width/image.naturalWidth,canvas.height/image.naturalHeight),w=image.naturalWidth*s,h=image.naturalHeight*s;ctx.drawImage(image,(canvas.width-w)/2,(canvas.height-h)/2,w,h);current=nearest;canvas.style.opacity='1';}document.querySelectorAll('[data-drift]').forEach(el=>{const r=el.getBoundingClientRect();el.style.transform=`translateX(${Math.max(-1,Math.min(1,(innerHeight-r.top)/innerHeight))*Number(el.dataset.drift)}px)`;});document.querySelector('.orbit').style.transform=`rotate(${scrollY*.025}deg)`;}
  function schedule(){if(!scheduled){scheduled=true;requestAnimationFrame(draw);}}
  async function load(){if(loading||paused)return;loading=true;const token=++generation,queue=[0];for(let i=4;i<FRAME_COUNT;i+=4)queue.push(i);for(let i=1;i<FRAME_COUNT;i++)if(i%4)queue.push(i);async function worker(){while(queue.length&&token===generation&&!paused){const index=queue.shift();await new Promise(resolve=>{const image=new Image();image.decoding='async';image.onload=async()=>{try{await image.decode();}catch{}if(token===generation){images[index]=image;schedule();}resolve();};image.onerror=resolve;image.src=`public/frames/${folder}/frame_${String(index+1).padStart(4,'0')}.webp`;});}}await Promise.all(Array.from({length:CONCURRENCY},worker));if(token===generation)loading=false;}
  function setPaused(value){paused=Boolean(value);toggle.setAttribute('aria-pressed',String(paused));toggle.setAttribute('aria-label',paused?'Resume background motion':'Pause background motion');toggle.textContent=paused?'Resume motion ▶':'Pause motion Ⅱ';if(paused){canvas.style.opacity='0';generation++;loading=false;}else{current=-1;load();schedule();}}
  toggle.addEventListener('click',()=>setPaused(!paused));motionQuery.addEventListener('change',e=>setPaused(e.matches||constrained));addEventListener('scroll',schedule,{passive:true});let resize;addEventListener('resize',()=>{clearTimeout(resize);resize=setTimeout(()=>{const next=innerWidth<768?'mobile':'desktop';if(next!==folder){folder=next;generation++;images=[];loading=false;load();}size();schedule();},160);});
  document.querySelectorAll('[data-dots]').forEach(group=>{for(let i=0;i<Number(group.dataset.dots);i++){const dot=document.createElement('i');dot.style.setProperty('--delay',`${i*30}ms`);group.append(dot);}});
  if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){if(!motionQuery.matches){entry.target.classList.add('entering');setTimeout(()=>entry.target.classList.remove('entering'),1600);}observer.unobserve(entry.target);}}),{threshold:.2});document.querySelectorAll('.chart').forEach(chart=>observer.observe(chart));}
  size();setPaused(paused);document.fonts?.ready.then(schedule);
})();
